# SPDX-FileCopyrightText: 2026 Noyalib
# SPDX-License-Identifier: MIT OR Apache-2.0

version = 1

[[annotations]]
path = [
    ".editorconfig",
    ".gitattributes",
    ".gitignore",
    ".rustfmt.toml",
    "Cargo.toml",
    "Cargo.lock",
    "deny.toml",
    "osv-scanner.toml",
    "rust-toolchain.toml",
    "REUSE.toml",
    "supply-chain/audits.toml",
    "supply-chain/config.toml",
    "supply-chain/imports.lock",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Noyalib"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ".github/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Noyalib"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ["README.md", "CHANGELOG.md", "SECURITY.md", "doc/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Noyalib"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = "examples/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Noyalib"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = "tests/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Noyalib"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = "benches/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Noyalib"
SPDX-License-Identifier = "MIT OR Apache-2.0"
